export const GET_SCHEDULES = 'GET_SCHEDULES';
export const CREATE_CALENDAR = 'CREATE_CALENDAR';
export const SELECT_CALENDAR = 'SELECT_CALENDAR';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const ADD_EVENT = 'ADD_EVENT';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const SCHEDULE_ERROR = 'SCHEDULE_ERROR';
export const EVENT_ERROR = 'EVENT_ERROR';
export const GET_EVENTS = 'GET_EVENTS';
export const DELETE_EVENT = 'DELETE_SCHEDULE';
export const CREATE_DRAGGABLE = 'CREATE_DRAGGABLE';
export const SET_LOADING = 'SET_LOADING';

